development:
  adapter: postgresql
  encoding: utf8
  database: pkp_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pkp_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: pkp_production
  pool: 5
